"""Tests for the agent fingerprinter."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

from typer.testing import CliRunner

from canary_cage.cli import app
from canary_cage.diff import compute_diff
from canary_cage.fingerprint import (
    Fingerprinter,
    FireContext,
    context_from_canary,
    identify_for_canary_id,
)
from canary_cage.state import CageState, PlantedCanary, save_state

runner = CliRunner()


def _ctx(**overrides) -> FireContext:
    defaults = dict(canary_id="abc123", canary_type="markdown", path="README.md")
    defaults.update(overrides)
    return FireContext(**defaults)


def test_clear_single_agent_match_claude():
    """A commit signed by Claude Code should rank claude-code first with
    multiple signals."""
    ctx = _ctx(
        commit_message=(
            "Refactor scanner module\n\n"
            "🤖 Generated with [Claude Code](https://claude.com/code)\n"
            "Co-Authored-By: Claude <noreply@anthropic.com>"
        ),
        commit_author="Claude <noreply@anthropic.com>",
    )
    report = Fingerprinter().identify(ctx)
    assert report.top is not None
    assert report.top.agent == "claude-code"
    assert report.top.confidence > 0.5
    # At least a few rules should have matched.
    assert len(report.top.signals) >= 3


def test_clear_single_agent_match_copilot_via_user_agent():
    ctx = _ctx(user_agent="github-copilot-agent/1.2.0", commit_author="copilot[bot]")
    report = Fingerprinter().identify(ctx)
    assert report.top is not None
    assert report.top.agent == "github-copilot"
    assert any("user_agent" in s or "copilot" in s for s in report.top.signals)


def test_ambiguous_multi_candidate_ranking():
    """A commit that pings both Cursor- and generic-LLM rules should
    return multiple ranked candidates with Cursor on top (heavier weight)."""
    ctx = _ctx(
        commit_message="[cursor] ✨ ai-generated refactor",
        commit_author="cursor[bot]",
    )
    report = Fingerprinter().identify(ctx)
    agents = [c.agent for c in report.candidates]
    assert "cursor" in agents
    assert "generic-llm" in agents
    # Cursor should outrank generic-llm.
    assert agents.index("cursor") < agents.index("generic-llm")


def test_no_match_returns_empty_candidates():
    ctx = _ctx(
        commit_message="fix: typo in README",
        commit_author="Alice <alice@example.com>",
    )
    report = Fingerprinter().identify(ctx)
    assert report.candidates == []
    assert report.top is None
    # to_dict must still produce a stable shape.
    d = report.to_dict()
    assert d == {"top": None, "candidates": []}


def test_to_dict_schema_stability():
    ctx = _ctx(
        commit_message="Generated by Cursor agent",
        commit_author="cursoragent",
    )
    report = Fingerprinter().identify(ctx)
    payload = report.to_dict()
    # Required keys.
    assert set(payload.keys()) == {"top", "candidates"}
    assert set(payload["top"].keys()) == {"agent", "confidence"}
    for cand in payload["candidates"]:
        assert set(cand.keys()) == {"agent", "display", "confidence", "signals"}
        assert isinstance(cand["confidence"], float)
        assert 0.0 <= cand["confidence"] <= 1.0


def test_override_pack_at_repo_root(tmp_path: Path):
    (tmp_path / "fingerprints.json").write_text(
        json.dumps(
            {
                "version": 1,
                "agents": [
                    {
                        "agent": "rybot",
                        "display": "RyBot",
                        "rules": [
                            {
                                "id": "rybot.author",
                                "weight": 0.6,
                                "field": "commit_author",
                                "pattern": "rybot",
                            }
                        ],
                    }
                ],
            }
        ),
        encoding="utf-8",
    )
    fp = Fingerprinter(root=tmp_path)
    report = fp.identify(_ctx(commit_author="rybot"))
    assert report.top is not None
    assert report.top.agent == "rybot"


def _init_git_repo(
    path: Path,
    *,
    author_name: str,
    author_email: str,
    commit_msg: str,
    file_rel: str,
    content: str,
):
    subprocess.run(["git", "init", "-q", "-b", "main", str(path)], check=True)
    env = {
        "GIT_AUTHOR_NAME": author_name,
        "GIT_AUTHOR_EMAIL": author_email,
        "GIT_COMMITTER_NAME": author_name,
        "GIT_COMMITTER_EMAIL": author_email,
        "GIT_CONFIG_GLOBAL": "/dev/null",
        "GIT_CONFIG_SYSTEM": "/dev/null",
        "HOME": str(path),
    }
    (path / file_rel).parent.mkdir(parents=True, exist_ok=True)
    (path / file_rel).write_text(content, encoding="utf-8")
    subprocess.run(["git", "-C", str(path), "add", "-A"], check=True, env=env)
    subprocess.run(["git", "-C", str(path), "commit", "-q", "-m", commit_msg], check=True, env=env)


def test_context_from_canary_pulls_git_commit(tmp_path: Path):
    _init_git_repo(
        tmp_path,
        author_name="Claude",
        author_email="noreply@anthropic.com",
        commit_msg="docs: tweak readme\n\n🤖 Generated with [Claude Code]",
        file_rel="README.md",
        content="hello",
    )
    canary = PlantedCanary(id="c1", type="markdown", path="README.md", marker="abcd1234")
    save_state(tmp_path, CageState(canaries=[canary]))

    ctx = context_from_canary(tmp_path, canary)
    assert ctx.commit_message and "Claude" in ctx.commit_message
    assert ctx.commit_author and "anthropic.com" in ctx.commit_author

    report = Fingerprinter(root=tmp_path).identify(ctx)
    assert report.top is not None
    assert report.top.agent == "claude-code"


def test_compute_diff_includes_attributed_to(tmp_path: Path):
    _init_git_repo(
        tmp_path,
        author_name="Cursor Agent",
        author_email="cursoragent@cursor.sh",
        commit_msg="[cursor] tweak",
        file_rel="docs/notes.md",
        content="hello",
    )
    canary = PlantedCanary(
        id="c-removed", type="markdown", path="docs/notes.md", marker="zzz999"
    )
    save_state(tmp_path, CageState(canaries=[canary]))

    report = compute_diff(tmp_path)
    assert len(report.diffs) == 1
    d = report.diffs[0]
    # No BEGIN sentinel in file → REMOVED verdict, which should be attributed.
    assert d.verdict == "removed"
    assert d.attributed_to is not None
    assert d.attributed_to["top"]["agent"] == "cursor"

    # JSON payload exposes the additive field.
    payload = report.to_dict()
    item = payload["groups"][0]["items"][0]
    assert "attributed_to" in item
    assert item["attributed_to"]["top"]["agent"] == "cursor"


def test_identify_for_canary_id_returns_none_for_unknown(tmp_path: Path):
    save_state(tmp_path, CageState(canaries=[]))
    assert identify_for_canary_id(tmp_path, "does-not-exist") is None


def test_each_agent_has_at_least_four_rules():
    """Acceptance: 4+ distinct heuristic rules per agent class."""
    fp = Fingerprinter()
    for agent in fp.pack["agents"]:
        assert (
            len(agent["rules"]) >= 4
        ), f"{agent['agent']} has only {len(agent['rules'])} rules"


def test_fingerprint_cli_json(tmp_path: Path, monkeypatch):
    _init_git_repo(
        tmp_path,
        author_name="copilot[bot]",
        author_email="copilot[bot]@users.noreply.github.com",
        commit_msg="chore: bump deps",
        file_rel="README.md",
        content="hello",
    )
    canary = PlantedCanary(id="c1", type="markdown", path="README.md", marker="m1")
    save_state(tmp_path, CageState(canaries=[canary]))

    result = runner.invoke(
        app, ["fingerprint", "c1", "--root", str(tmp_path), "--json"]
    )
    assert result.exit_code == 0, result.stdout
    payload = json.loads(result.stdout)
    assert payload["canary_id"] == "c1"
    assert payload["attributed_to"]["top"]["agent"] == "github-copilot"


def test_fingerprint_cli_unknown_id(tmp_path: Path):
    save_state(tmp_path, CageState(canaries=[]))
    result = runner.invoke(app, ["fingerprint", "nope", "--root", str(tmp_path)])
    assert result.exit_code == 2


def test_check_json_includes_attributed_to(tmp_path: Path):
    _init_git_repo(
        tmp_path,
        author_name="Claude",
        author_email="noreply@anthropic.com",
        commit_msg="docs: tweak\n\n🤖 Generated with [Claude Code]",
        file_rel="README.md",
        content="hello",
    )
    canary = PlantedCanary(id="c1", type="markdown", path="README.md", marker="m1")
    save_state(tmp_path, CageState(canaries=[canary]))

    result = runner.invoke(app, ["check", "--root", str(tmp_path), "--json"])
    # Fires were detected → exit 1, but stdout still has JSON.
    assert result.exit_code in (0, 1)
    payload = json.loads(result.stdout)
    assert "fires" in payload
    fires = payload["fires"]
    assert fires, "expected at least one fire"
    # Working-tree fire on c1 should be attributed to claude-code.
    f = next(f for f in fires if f["canary_id"] == "c1")
    assert f["attributed_to"] is not None
    assert f["attributed_to"]["top"]["agent"] == "claude-code"
