"""Composite-action entrypoint for `canary check`.

Reads inputs from environment variables set by `action.yml`, runs
``canary check --json``, writes:

* ``$RUNNER_TEMP/canary-cage/report.json``  — full structured payload
* ``$RUNNER_TEMP/canary-cage/pr-comment.md`` — pretty markdown for PR/comment
* ``$GITHUB_STEP_SUMMARY`` — same markdown, appended to the job summary
* ``$GITHUB_OUTPUT`` — ``fired-count``, ``fired-ids``, ``report-path``,
  ``fired-dir``, ``comment-path``

Exit code:

* ``0`` when clean, or when ``fail-on-fire`` is falsy
* ``1`` when at least one canary fired and ``fail-on-fire`` is truthy
* ``2`` when ``canary check`` itself errored (invalid config, etc.)

The script is small on purpose so the tests in
``tests/test_action_runner.py`` can exercise it end-to-end with a
stubbed ``canary`` executable and temporary directories standing in for
``$RUNNER_TEMP``/``$GITHUB_OUTPUT``/``$GITHUB_STEP_SUMMARY``.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

TRUTHY = {"true", "1", "yes", "on"}


def _truthy(value: str | None) -> bool:
    return (value or "").strip().lower() in TRUTHY


def _emit_outputs(github_output: Path | None, values: dict[str, str]) -> None:
    if github_output is None:
        return
    with github_output.open("a", encoding="utf-8") as fh:
        for key, val in values.items():
            if "\n" in val:
                # Use heredoc format for multi-line values (per GitHub docs).
                delim = "EOF_CANARY_CAGE"
                fh.write(f"{key}<<{delim}\n{val}\n{delim}\n")
            else:
                fh.write(f"{key}={val}\n")


def _append_summary(step_summary: Path | None, text: str) -> None:
    if step_summary is None:
        return
    with step_summary.open("a", encoding="utf-8") as fh:
        fh.write(text)
        if not text.endswith("\n"):
            fh.write("\n")


def build_markdown(payload: dict) -> str:
    """Render the fire report as GitHub-flavoured markdown."""

    fires = payload.get("fires") or []
    lines: list[str] = ["<!-- canary-cage:pr-comment -->"]
    if not fires:
        lines.append("## 🐤 canary-cage: all quiet")
        lines.append("")
        lines.append(
            "No canaries fired against this checkout. "
            "The birds are still singing."
        )
        return "\n".join(lines) + "\n"

    lines.append(f"## 🚨 canary-cage: {len(fires)} canary fire(s) detected")
    lines.append("")
    lines.append(
        "One or more canaries planted in this repository were tripped. "
        "Review the table below and inspect the `canary-cage-fires` "
        "workflow artifact for the raw beacon payloads."
    )
    lines.append("")
    lines.append("| Canary ID | Type | Source | Path | Detail |")
    lines.append("| --- | --- | --- | --- | --- |")
    for fire in fires:
        cid = str(fire.get("canary_id", "?"))
        ctype = str(fire.get("canary_type", "?"))
        source = str(fire.get("source", "?"))
        path = str(fire.get("path") or "—")
        detail = str(fire.get("detail") or "").replace("|", "\\|").replace("\n", " ")
        if len(detail) > 160:
            detail = detail[:157] + "…"
        lines.append(f"| `{cid}` | {ctype} | {source} | `{path}` | {detail} |")

    attributed = [f for f in fires if f.get("attributed_to")]
    if attributed:
        lines.append("")
        lines.append("### Suspected agents")
        lines.append("")
        lines.append("| Canary ID | Agent | Confidence |")
        lines.append("| --- | --- | --- |")
        for fire in attributed:
            attr = fire.get("attributed_to") or {}
            top = attr.get("top") or {}
            agent = str(top.get("agent") or top.get("display") or "?")
            conf = top.get("confidence")
            conf_txt = f"{conf:.2f}" if isinstance(conf, (int, float)) else "—"
            lines.append(f"| `{fire.get('canary_id', '?')}` | {agent} | {conf_txt} |")

    lines.append("")
    lines.append(
        "> _Generated by the [`canary-cage`](https://github.com/rwrife/canary-cage) "
        "GitHub Action._"
    )
    return "\n".join(lines) + "\n"


def run(argv: list[str] | None = None, env: dict[str, str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--canary-bin",
        default=None,
        help="Override the canary executable (test hook).",
    )
    args = parser.parse_args(argv)
    env = dict(os.environ if env is None else env)

    config_path = env.get("CANARY_CAGE_CONFIG", "canary.toml")
    fail_on_fire = _truthy(env.get("CANARY_CAGE_FAIL_ON_FIRE", "true"))
    workdir_raw = env.get("CANARY_CAGE_WORKDIR", "").strip()
    workdir = Path(workdir_raw) if workdir_raw else Path(env.get("GITHUB_WORKSPACE", "."))
    runner_temp = Path(env.get("RUNNER_TEMP") or tempfile.gettempdir()) / "canary-cage"
    runner_temp.mkdir(parents=True, exist_ok=True)

    report_path = runner_temp / "report.json"
    comment_path = runner_temp / "pr-comment.md"
    fired_dir = workdir / ".canary-cage" / "fired"

    github_output = Path(env["GITHUB_OUTPUT"]) if env.get("GITHUB_OUTPUT") else None
    step_summary = Path(env["GITHUB_STEP_SUMMARY"]) if env.get("GITHUB_STEP_SUMMARY") else None

    canary_bin = args.canary_bin or env.get("CANARY_CAGE_BIN") or "canary"
    cmd = [canary_bin, "check", "--root", str(workdir), "--json"]

    # Note the config path in the log so debugging is obvious. `canary check`
    # discovers ``canary.toml`` inside ``--root`` automatically today; the
    # explicit path is surfaced for future use and to fail loudly when the
    # user pointed at a config that isn't there.
    if Path(config_path).is_absolute():
        resolved_config = Path(config_path)
    else:
        resolved_config = workdir / config_path
    print(f"canary-cage action: workdir={workdir}", file=sys.stderr)
    print(
        f"canary-cage action: config={resolved_config} "
        f"(exists={resolved_config.exists()})",
        file=sys.stderr,
    )

    try:
        proc = subprocess.run(
            cmd,
            cwd=str(workdir),
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError as exc:
        print(f"canary-cage action: could not exec {canary_bin!r}: {exc}", file=sys.stderr)
        return 2

    stdout = proc.stdout or ""
    stderr = proc.stderr or ""
    if stderr.strip():
        # Surface warnings/errors in the runner log without failing the build.
        print(stderr, file=sys.stderr)

    payload: dict
    try:
        payload = json.loads(stdout) if stdout.strip() else {"fires": []}
    except json.JSONDecodeError as exc:
        print(
            "canary-cage action: could not parse JSON from `canary check --json` "
            f"(rc={proc.returncode}, err={exc}). Raw stdout follows:",
            file=sys.stderr,
        )
        print(stdout, file=sys.stderr)
        return 2

    fires = payload.get("fires") or []
    # `canary check` exits 1 when fires are found — that's expected. Anything
    # else (2, config errors, uncaught exception) means we couldn't get a
    # trustworthy answer, so fail loudly rather than silently pass.
    if proc.returncode not in (0, 1):
        print(
            f"canary-cage action: `canary check` failed (rc={proc.returncode}). "
            "See stderr above.",
            file=sys.stderr,
        )
        return 2

    report_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    markdown = build_markdown(payload)
    comment_path.write_text(markdown, encoding="utf-8")

    fired_ids = [str(f.get("canary_id", "")) for f in fires if f.get("canary_id")]
    outputs = {
        "fired-count": str(len(fires)),
        "fired-ids": json.dumps(fired_ids),
        "report-path": str(report_path),
        "fired-dir": str(fired_dir),
        "comment-path": str(comment_path),
    }
    _emit_outputs(github_output, outputs)
    _append_summary(step_summary, markdown)

    if fires:
        print(
            f"canary-cage action: {len(fires)} canary fire(s) detected — "
            f"see {report_path}",
            file=sys.stderr,
        )
    else:
        print("canary-cage action: no fires detected — all quiet.", file=sys.stderr)

    if fires and fail_on_fire:
        return 1
    return 0


def main() -> None:  # pragma: no cover - trivial wrapper
    sys.exit(run())


if __name__ == "__main__":  # pragma: no cover - runtime entrypoint
    main()
